### ISSUE TITLE
Support Android App Bundles

### ISSUE THREAD

**Issue by jeremistadler** [bitrise-steplib/bitrise-step-android-build#9]
https://developer.android.com/platform/technology/app-bundle/

Gradle can build bundle files with
`./gradlew bundleRelease`
instead of 
`./gradlew assembleRelease`

Is it possible to build app bundles with bitrise?

**Comment by bitce** [comment]
Hi @jeremistadler, yes, that's entirely correct!

**Comment by jeremistadler** [comment]
I can't seem to find the config option for it. Started using `Gradle Runner` step instead.

**Comment by fehersanyi-bitrise** [comment]
Hy @jeremistadler that would be the correct approach, also change the export configs from apk to aab 🙃

**Comment by jeremistadler** [comment]
For other people having the same issue. 
Use the `Gradle Runner` step instead of `Android Build`
My config for a react-native project looks like this
```
- gradle-runner:
        inputs:
        - apk_file_include_filter: "*.aab"
        - gradlew_path: "./android/gradlew"
        - gradle_options: "--stacktrace --no-daemon --project-dir ./android/"
        - gradle_task: bundleRelease
```
